name: CI to Docker Hub and GitHub Packages

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/my-app:latest
          load: true # Nécessaire pour que Trivy puisse scanner l'image

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/my-app:latest'
          format: 'table'
          exit-code: '0' # Ignorer le code de sortie de Trivy

      - name: Push Docker image to GitHub Packages
        if: success() # Cette étape s'exécutera seulement si le scan Trivy a réussi
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/my-app:latest
